plugins {
    id 'com.android.application'
}

android {
    namespace 'com.peter.hc15profilediag'
    compileSdk 35

    defaultConfig {
        applicationId 'com.peter.hc15profilediag'
        minSdk 34
        targetSdk 35
        versionCode 2
        versionName '0.1.1'
    }

    buildTypes {
        debug {
            minifyEnabled false
        }
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }

    applicationVariants.configureEach { variant ->
        variant.outputs.configureEach { output ->
            output.outputFileName = "HC15ProfileDiagnostic-V0.1.1-${variant.buildType.name}.apk"
        }
    }
}
